### ISSUE TITLE
[SUGGESTION] Command to toggle resource pack alert on join

### ISSUE THREAD

**Issue by srnyx** [christopherwalkerml/DeepStoragePlus#7]
I have the resource pack downloaded and always enabled on my client.
But, I still get this annoying error when joining the server:
![img](https://us.tixte.net/uploads/srnyx.needs.rest/ks0h8fgpv9a.png)

My suggestion is to have a command like `/dsp alert` (and `/dsp alert on` and `/dsp alert off`) that will toggle the join alert.

**Comment by christopherwalkerml** [comment]
there is a config option to disable it for everybody. you can provide the download link yourself if you do this

**Comment by srnyx** [comment]
> there is a config option to disable it for everybody.

I still want the alert though, I just want people that have the resource pack on their client to be able to toggle it.

> you can provide the download link yourself if you do this

It seems kinda unnecessary for me to have to find a way to display the alert **and** add a way for people to toggle it (no clue how I would do this).

**Comment by srnyx** [comment]
Players can set this when editing a server in the Multiplayer tab
