### ISSUE TITLE
Use UUIDs instead of player names

### ISSUE THREAD

**Issue by srnyx** [christopherwalkerml/DeepStoragePlus#8]

**Comment by christopherwalkerml** [comment]
not sure what youre asking here.
DSUs already store the owner's UUID

**Comment by srnyx** [comment]
> not sure what youre asking here.
> DSUs already store the owner's UUID

When a player on my server changed their username, they were unable to access their DSUs.
It said the owner was `LordMendalton`, and his new username was `Mendalton`.
So not sure if it really does store with UUIDs.

**Comment by christopherwalkerml** [comment]
when did they change their username? I only added the UUID feature in the last update. If they never opened their DSU after the update then it wouldnt have stored the UUID

**Comment by srnyx** [comment]
> when did they change their username? I only added the UUID feature in the last update. If they never opened their DSU before the update then it wouldnt have stored the UUID

Ah, that must be why. They changed it on 9/4
